config/routes.rb
Rails.application.routes.draw do
  get 'home/landing'

  resources :interfaces do
    resources :notes, shallow: true
    get 'check_pulse'
  end


  resources :users do
    get 'settings', to: 'settings#edit'
    put 'update', to: 'settings#update'
    collection do
      get 'support'
      get 'plan'
      get 'billing'
      get 'notifications'
      get 'support'
    end

    member do
      get 'profile'
      get 'notifications'
      get 'dashboard'
      get 'billing'
      get 'plan'
    end
  end

  get '/google_login'=>'sessions#google_login'
  get '/auth/:provider/callback'=>'sessions#create'
  get '/signin'=>'sessions#new', :as=>:signin
  post '/login'=>'sessions#login', as: 'pw_login'
  get '/signout'=>'sessions#destroy', :as=>:signout
  get '/auth/failure'=>'sessions#failure'

  root to: 'home#landing'
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :interface
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_interface, only: [:new]

  def index
    interface = Interface.find(notes_params[:interface_id])
    if interface.nil?
      return interfaces_path, error: 'int id missing'
    end
    render partial: 'index', locals: {notes: Note.all, interface: interface}
  end

  def new
    interface = Interface.find(notes_params[:interface_id])
    render partial: 'new', locals: {interface: interface, note: Note.new }
  end

  def create
    results = {}
    note = Note.new(notes_params)
    note.created_by = current_user.id
    if note.save!
      results[:notice] = 'Note saved.'
    else
      results[:notice] = 'Note fail.'
    end
    # redirect_to interfaces_path
    render json: results
  end

  private
  def set_interface
    @interface = Interface.find_by(id: notes_params[:interface_id])
    byebug if @interface.nil?
  end

  def notes_params
    params.permit(:interface_id, :content, :type)
  end
end

app/views/notes/_index.html.erb
<% if local_assigns[:notes] %>
  <% notes.each do |note| %>
    <div><%= note.content %></div>
  <% end %>
<% end %>


<script type="text/javascript" charset="utf-8">
  $(function () {
    $('.new-note-btn').on('click', function (e) {
      e.preventDefault();
      $.get('<%= new_interface_note_path(1) %>').done(function (response) {
        $('.modal-body').html(response);
      })
    })


  })
</script>

app/views/notes/_new.html.erb
<%= form_with url: interface_notes_path, class: 'note-form' do |f| %>
  <%= f.label :content, class: 'control-label' do %>
    <%= f.text_field :content, class: 'form-control' %>
  <% end %>
  <div class="checkbox checkbox-success form-check form-check-inline">
    <input id="encrypted" type="checkbox">
    <label for="encrypted" style="margin-left:15px;">Encrypt it</label>
  </div>

  <div class="modal-footer">
    <div class="container">
      <div class="row">
        <div class="offset-md-9 col-md-3 pull-right">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= submit_tag 'Save', class: 'save-btn btn btn-success btn-fill' %>
        </div>
      </div>
    </div>
  </div>



<% end %>


<script type="text/javascript" charset="utf-8">
  $(function () {
    $('.save-btn').on('click', function (e) {
      e.preventDefault();
      let $form = $('form.note-form');
      let url = '<%= interface_notes_path(@interface) %>';
      let data = $form.serialize();
      $.post(url, data).always(function (response) {
        $.notify(response.notice);
        $('#notes-modal').modal('hide');
      })
    })
  })
</script>

app/views/notes/_notes_modal.html.erb
<div class="modal fade" id="notes-modal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Notes</h4>
          <%= button_to 'New Note', '#', class: 'btn btn-info new-note-btn'%>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>