config/routes.rb
Rails.application.routes.draw do
  get 'home/landing'

  resources :interfaces do
    resources :notes, shallow: true
    get 'check_pulse'
  end


  resources :users do
    get 'settings', to: 'settings#edit'
    put 'update', to: 'settings#update'
    collection do
      get 'support'
      get 'plan'
      get 'billing'
      get 'notifications'
      get 'support'
    end

    member do
      get 'profile'
      get 'notifications'
      get 'dashboard'
      get 'billing'
      get 'plan'
    end
  end

  get '/google_login'=>'sessions#google_login'
  get '/auth/:provider/callback'=>'sessions#create'
  get '/signin'=>'sessions#new', :as=>:signin
  post '/login'=>'sessions#login', as: 'pw_login'
  get '/signout'=>'sessions#destroy', :as=>:signout
  get '/auth/failure'=>'sessions#failure'

  root to: 'home#landing'
end

app/models/settings.rb
class Settings < ApplicationRecord
  belongs_to :user
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
before_action :grab_or_make, only: [:edit, :update]
  def edit
  end

  def update
    byebug
    @settings.assign_attributes(settings_params)
    if params[:unsubscribed] == 'on'
      @settings.update(unsubscribed: true)
    else
      @settings.update(unsubscribed: false)
    end
    respond_to do |format|
      format.html do
        redirect_to interfaces_path, notice: 'Saved changes.'
      end
      format.json do
      end
    end
  end

  private

  def grab_or_make
    @settings = Settings.find_or_create_by(user_id: settings_params[:user_id])
  end

  def settings_params
    params.permit(:unsubscribed, :user_id)
  end

end

app/views/settings/_edit.html.erb
<div class="modal fade" id="settings-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Settings</h4>
      </div>
      <div class="modal-body">
        <%= form_tag user_update_path(current_user), method: 'put', class: 'settings-form' do %>
          <div class="form-group">
            <%= label_tag :refresh_interval, 'Refresh Interval', class: 'control-label pull-left' %>
            <span class="pull-right">
                <%= select_tag :refresh_interval, options_for_select(['Manual', 2, 5, 30, 60]), disabled: 'disabled' %>
              <span class="mlh">min</span>
            </span>
          </div>
          <div class="clearfix"></div>
          <div class="form-group row">
            <span class="col-sm-10">
              Unsubscribe
            </span>
            <span class="col-sm-push-11 col-sm-1">
            <input type="checkbox" name="unsubscribe" class="bootstrap-switch pull-right unsub-toggle" data-on-color="danger"/>
            </span>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= button_tag 'Save', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>