config/routes.rb
Rails.application.routes.draw do
  get 'home/landing'

  resources :interfaces do
    resources :notes, shallow: true
    get 'check_pulse'
  end


  resources :users do
    get 'settings', to: 'settings#edit'
    put 'update', to: 'settings#update'
    collection do
      get 'support'
      get 'plan'
      get 'billing'
      get 'notifications'
      get 'support'
    end

    member do
      get 'profile'
      get 'notifications'
      get 'dashboard'
      get 'billing'
      get 'plan'
    end
  end

  get '/google_login'=>'sessions#google_login'
  get '/auth/:provider/callback'=>'sessions#create'
  get '/signin'=>'sessions#new', :as=>:signin
  post '/login'=>'sessions#login', as: 'pw_login'
  get '/signout'=>'sessions#destroy', :as=>:signout
  get '/auth/failure'=>'sessions#failure'

  root to: 'home#landing'
end

app/models/interface.rb
class Interface < ApplicationRecord
  belongs_to :user
  has_many :notes
  has_one :settings
  attr_accessor :hostname

  validates_format_of :ip, with: /(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/,
                      message:   ' needs to be in valid IP format'
  validates_format_of :ddns, with: /^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$/,
                      message:     'address is invalid', multiline: true, allow_blank: true

  def alive?
    service = ExternalIPService.new
    service.check_for_life(ip)
  end

  def ui_life_status
    last_response.present? ? 'Active' : 'Dead'
  end

   def ip_port
    port ? self.ip + ':' + self.port.to_s : self.ip
  end
end

app/controllers/interfaces_controller.rb
class InterfacesController < ApplicationController
  layout "application"
  layout 'sidenav'

  before_action :set_interface, except: [:index, :create, :new]

  def index
    @body_class = 'with-sidebar show-sidebar'
    @interfaces = Interface.all.order(ip: :asc)
  end

  def new
    @body_class = 'with-sidebar show-sidebar'
    @interface = Interface.new
  end

  def edit
    @body_class = 'with-sidebar show-sidebar'
  end

  def create
    @interface = Interface.new(interface_params)
    @interface.assign_attributes(user_id: current_user.id, last_responded_at: Time.current)
    if @interface.save
      redirect_to interfaces_path, notice: 'Interface created.'
    else
      render :new
    end
  end

  # PATCH/PUT /interfaces/1
  def update
    @interface.assign_attributes(user_id: current_user.id, last_responded_at: Time.current)
    if @interface.update!(interface_params)
      redirect_to interfaces_path, notice: 'Changes Saved..'
    else
      flash.now[:error] = 'erroredit'
      render :edit
    end
  end

  # DELETE /interfaces/1
  def destroy
    @interface.destroy
    redirect_to interfaces_url, notice: 'Interface was destroyed.'
  end

  def check_pulse
    result = ExternalIPService.new.check_for_life(@interface)
    render json: {status: result}
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interface
      @interface = Interface.find_by(id: params[:id])
      if @interface.nil?
        @interface = Interface.find_by(id: params[:interface_id])
      end
    end

    # Only allow a trusted parameter "white list" through.
    def interface_params
      params.require(:interface).permit(:ip, :ddns, :port)
    end
end

app/helpers/interfaces_helper.rb
module InterfacesHelper
end

app/views/interfaces/_form.html.erb
<%= form_for(@interface, html: {class: 'form-horizontal'}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="form-group row">
      <%= f.label :ip, class: 'col-md-6 col-xs-12 control-label' do %>
        IP Address
        <%= f.text_field :ip, class: 'form-control is-invalid ip-field', placeholder: 'ex: 192.168.1.1', required: true, pattern: "(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])" %>
      <% end %>

      <%= f.label :ddns, class: 'control-label col-md-6 col-xs-12' do %>
        DDNS
        <%= f.text_field :ddns, class: 'form-control', placeholder: 'Optional' %>
      <% end %>
    </div>
    <div class="form-group row">
      <%= f.label :hostname, class: 'control-label col-xs-12 col-md-6' do %>
        Hostname
        <%= f.text_field :hostname, class: 'form-control', placeholder: 'Optional' %>
      <% end %>

      <%= f.label :port, class: 'control-label col-xs-12 col-md-6' do %>
        Port
        <%= f.number_field :port, class: 'form-control', placeholder: 'Optional' %>
      <% end %>
    </div>
  </div>

  <div class="d-flex">
    <div class="ml-auto">
      <%= link_to "Cancel", interfaces_path, class: 'btn  btn-danger' %>
      <%= f.submit 'Save', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
$(function(){
  let ipfield = document.querySelector('.ip-field')
  toggleValidity(ipfield)
})
</script>

app/views/interfaces/edit.html.erb
<% @title = "Edit Interface" %>

<%# content_for :description do %>
<!--  Make updates -->
  <%# end %>

<div class="container">
  <div class="row">
    <div class="col-12 col-md-9">
      <div class="card card-sheet">
        <div class="card-body">
          <div class="container">
            <%= render 'form' %>
            <div class="delete-btn"></div>
          </div>
        </div>
      </div>
    </div>

<!--    <div id="sidebar" class="col-md-3">-->
<!--      <ul class="nav nav-stacked nav-caret-left bg-gray-200 card small pb-2">-->
<!--        <li><h6 class="mt-3 ml-3">Sub Menu</h6></li>-->
<!--        <li class="nav-item">-->
<!--        <a class="nav-link" href="#">Vacation Days</a>-->
<!--        </li>-->
<!--        <li class="nav-item active">-->
<!--        <a class="nav-link" href="#">Salaries</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--        <a class="nav-link" href="#">Disciplinary Items</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--        <a class="nav-link" href="#">Firings</a>-->
<!--        </li>-->
<!--      </ul>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->

app/views/interfaces/index.html.erb
<div class="row">
  <div class="col-12">
    <div class="card card-default position-relative inspectable">
      <!-- component-title: Active Users Table -->
<!--      <div class="card-header">-->
<!--        <h6>Addresses</h6>-->
        <%#= link_to new_interface_path, class: 'btn btn-primary btn-circle add-interface' do %>
<!--          Add Interface &nbsp;-->
<!--          <i class="fa fa-plus" style="color: #2E354F;"></i>-->
        <%# end %>
<!--      </div>-->
      <div class="table-responsive">
        <table class="table table-hover table-striped">
          <thead>
          <tr>
            <th>#</th>
            <th>IP</th>
            <th>DDNS</th>
            <th>Status</th>
            <th>Port</th>
            <th class="center">Actions</th>
          </tr>
          </thead>

          <tbody>
          <% @interfaces.each do |interface| %>
            <tr>
              <td><%= interface.id %></td>
              <td>
                <strong class=""><%= link_to interface.ip, 'http://' + interface.ip_port, target: '_blank', style: 'text-decoration:none;color:#959FBD;' %></strong>
              </td>
              <td><%= interface.ddns %></td>
              <td>
                <% if interface.last_response %>
                  <span class="badge badge-success">Active</span>
                <% else %>
                  <span class="badge badge-danger"><%= time_ago_in_words(interface.last_responded_at) %></span>
                <% end %>
              </td>
              <td><%= interface.port %></td>
              <td>
                <div class="center  btn-group-xs">
                  <i class="fa fa-sticky-note fa-2x notes-btn clickable" data-int="<%= interface.id %>"></i>
                  <%= link_to edit_interface_path(interface) do %>
                    <i class=" center fa fa-pencil fa-2x middle"></i>
                  <% end %>
                  <%= link_to interface_check_pulse_path(interface) do %>
                    <i class="fa fa-refresh fa-2x " data-id="<%= interface.id %>"></i>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>
<%= render partial: 'notes/notes_modal', style: 'display:none;', id: 'notes-partial' %>

<script type="text/javascript" charset="utf-8">
  $(function () {
    $('.fa-refresh').on('click', function (e) {
      e.preventDefault();
      let $this = $(this);
      let id = $this.data('id');
      $this.addClass('fa-spin');
      $.get('interfaces/' + id + '/check_pulse', {interface_id: id}).always(function () {
        $this.removeClass('fa-spin');
        // difficult jump to get to badge
        $this.parents('td').siblings().children('span.badge').removeClass(('animated rubberBand')).addClass('animated rubberBand')
      })
    })
    $('.add-interface').on('click', function (e) {
    })

    $('.notes-btn').on('click', function () {
      $('#notes-partial').show();
      let id = $(this).data('int');
      console.log(id)
      $.get('/interfaces/' + id.toString() + '/notes').done(function (response) {
        $('#notes-modal').modal('show');
        $('#notes-modal .modal-body').html(response)
      }).fail(function () {
        $.notify('Error')
      })
    })
  })
</script>
<style>

  .fa {
    color: #959FBD;
  }

  .middle {
    margin: 0 20px;
  }
</style>

app/views/interfaces/new.html.erb
<% @title = "New interface" %>

<% content_for :description do %>
<% end %>

<div class="card">
  <div class="card-body">
    <%= render partial: 'form' %>
  </div>
</div>
<!--  validation form decoration -->
<!--<div class="card-body  ">-->
<!--  <div class="form-group">-->
<!--    <label class="control-label" for="inputSuccess1">Input with success</label>-->
<!--    <input type="text" class="form-control is-valid"-->
<!--    id="inputSuccess1" title="" autofill-prediction="UNKNOWN_TYPE">-->
<!--  </div>-->
<!--  <div class="form-group">-->
<!--    <label class="control-label" for="inputError1">Input with error</label>-->
<!--    <input type="text" class="form-control is-invalid"-->
<!--    id="inputError1" title="" autofill-prediction="EMAIL_ADDRESS">-->
<!--  </div>-->
<!--  <hr>-->
<!--  <legend>With Optional Icons</legend>-->
<!--  <div class="form-group has-success has-feedback">-->
<!--    <label class="control-label" for="inputSuccess2">Input with success</label>-->
<!--    <div class="form-group has-success">-->
<!--      <input type="email" value="Success Input" class="form-control form-control-success"-->
<!--      title="" autofill-prediction="EMAIL_ADDRESS">-->
<!--    </div>-->
<!--  </div>-->
<!--  <div class="form-group has-feedback">-->
<!--    <div class="form-group has-danger">-->
<!--      <input type="email" value="Error Input" class="form-control form-control-danger"-->
<!--      title="" autofill-prediction="EMAIL_ADDRESS">-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->




<!--      <div id="sidebar" class="col-12 col-md-3">-->
<!--        <ul class="nav nav-stacked nav-caret-left bg-gray-200 card small pb-2">-->
<!--          <li><h6 class="mt-3 ml-3">Sub Menu</h6></li>-->
<!--          <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Vacation Days</a>-->
<!--          </li>-->
<!--          <li class="nav-item active">-->
<!--          <a class="nav-link" href="#">Salaries</a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Disciplinary Items</a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Firings</a>-->
<!--          </li>-->
<!--        </ul>-->
<!--      </div>-->


<style>
</style>
<script type="text/javascript" charset="utf-8">
  $(function () {
  })
</script>

app/views/interfaces/show.html.erb
<% @title = "Showing interface" %>

<% content_for :description do %>
  <p>Edit this template in <code>app/views/interfaces/show.html.erb</code>.</p>
  <% end %>

<div class="container">
  <div class="row">
    <div class="col-12 col-md-9">
      <div class="card">
        <div class="card-body">
          <div class="form-horizontal">
                        <div class="d-flex">
              <div class="ml-auto">
                <%= link_to fa_icon_tag("pencil") + ' Edit', edit_interface_path(@interface), class: 'btn btn-primary' %>
                <%= link_to 'Back', interfaces_path, class: 'btn' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="sidebar" class="col-md-3">
      <ul class="nav nav-stacked nav-caret-left bg-gray-200 card small pb-2">
        <li><h6 class="mt-3 ml-3">Sub Menu</h6></li>
        <li class="nav-item">
        <a class="nav-link" href="#">Vacation Days</a>
        </li>
        <li class="nav-item active">
        <a class="nav-link" href="#">Salaries</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="#">Disciplinary Items</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="#">Firings</a>
        </li>
      </ul>
    </div>
  </div>
</div>