config/routes.rb
Rails.application.routes.draw do
  get 'home/landing'

  resources :interfaces do
    resources :notes, shallow: true
    get 'check_pulse'
  end


  resources :users do
    get 'settings', to: 'settings#edit'
    put 'update', to: 'settings#update'
    collection do
      get 'support'
      get 'plan'
      get 'billing'
      get 'notifications'
      get 'support'
    end

    member do
      get 'profile'
      get 'notifications'
      get 'dashboard'
      get 'billing'
      get 'plan'
    end
  end

  get '/google_login'=>'sessions#google_login'
  get '/auth/:provider/callback'=>'sessions#create'
  get '/signin'=>'sessions#new', :as=>:signin
  post '/login'=>'sessions#login', as: 'pw_login'
  get '/signout'=>'sessions#destroy', :as=>:signout
  get '/auth/failure'=>'sessions#failure'

  root to: 'home#landing'
end

app/views/layouts/_app_nav.html.erb
<%= render :layout => "layouts/base" do %>
  <nav class="navbar navbar-expand-lg">
    <%= link_to app_name, root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">Servers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
      <ul class="nav navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link" id="dropdownSearchButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= theme_icon_tag "search" %>
          </a>
          <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownSearchButton">
            <li>
              <form class="form-inline" role="search">
                <div class="input-group my-0">
                  <input type="text" class="form-control" id="searchbox" placeholder='Not yes working'>
                </div>
              </form>
            </li>
          </ul>
        </li>
        <li class="nav-item dropdown">
<!--          <a class="nav-link" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
            <%= theme_icon_tag "settings", class:'settings-btn' %>
<!--            <span class="caret caret-light"></span>-->
<!--          </a>-->
<!--          <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">-->
<!--            <li>-->
<!--              <a class="dropdown-item" href="#">Site management</a>-->
<!--            </li>-->
<!--            <li>-->
<!--              <a class="dropdown-item" href="#">User management</a>-->
<!--            </li>-->
<!--            <li>-->
<!--              <a class="dropdown-item" href="#">Settings</a>-->
<!--            </li>-->
<!--          </ul>-->
        </li>
        <li class="nav-item dropdown notifications">
          <a class="nav-link with-count" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= theme_icon_tag "bell" %>
            <span class="badge badge-sm">2</span>
            <span class="d-none d-xs-block">Notifications</span>
          </a>
          <ul class="dropdown-menu  dropdown-menu-right">
            <li class="dropdown-item">
              <div class="card">
                <div class="card-header text-center text-primary">
                  <strong>You have
                    <span>2</span>notifications</strong>
                </div>
                <div class="list-group">
                  <a href="#" class="list-group-item">
                    <div class="media">
                      <img class="d-flex mr-3 rounded-circle" width="32" height="32" src="/assets/rrt/stock/3-9b9d225ea3cf9c9f07cea81d16c455fb6248b9ccf19717395fbcc184411f0a89.jpg" alt="3">
                      <div class="media-body">
                        <p>My name is Inigo Montoya.</p>
                        <small class="text-muted d-block">10 minutes ago</small>
                      </div>
                    </div>
                  </a>
                  <a href="" class="media list-group-item">
                    <span class="media-body">
                      <div>
                        <p>You've reached your space quota!</p>
                        <div class="progress progress-sm m0">
                          <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
                            <span class="sr-only">100% Complete</span>
                          </div>
                        </div>
                      </div>
                      <small class="text-muted">12 hours ago</small>
                    </span>
                  </a>
                </div>
                <div class="card-footer">
                  <a href="#" class="pull-right">
                    <%= theme_icon_tag "settings" %>
                  </a>
                  <a href="#">View all Notifications</a>
                </div>
              </div>
            </li>
          </ul>
        </li>
        <li class="nav-item dropdown user-nav">
          <a class="nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="avatar rounded-circle" width="34" height="34" src="/assets/rrt/stock/4-36a07a4eb7045e8049c3529147e6f1383c0956e0e586e07927e356c18b6b7920.jpg" alt="4">
            <span class="caret caret-light"></span>
          </a>
          <ul class="dropdown-menu dropdown-menu-right" role="menu">
            <li class="dropdown-item text-center">
              <div class="card">
                <div class="card-body">
                  <img class="avatar img-rounded" width="120" height="120" src="/assets/rrt/stock/2-625f1b778bfa549542025e4c5c195a903aa82a0a0c72bdc85bc949fdca9aa5fb.jpg" alt="2">
                  <p class="m0 p0 d-block">Fill Murray</p>
                  <p class="small m0 p0">Premium Account</p>
                </div>
                <div class="card-footer d-flex justify-content-between">
                  <div>
                    <a href="003_app_pages@fa-laptop%2F006_user_profile" class="btn ">Edit Profile</a>
                  </div>
                  <div>
                    <%= link_to 'Logout', signout_path, class:'btn' %>

                  </div>
                </div>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
  <%= yield %>
<% end %>

app/views/layouts/_base.html.erb
<!DOCTYPE html>
<%= html_tag :lang => "en" do %>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%# Turbolinks... sigh. If you're going to remove this line, please make sure you know what
      you're doing. Please read very carefully: https://github.com/turbolinks/turbolinks %>
    <meta name="turbolinks-cache-control" content="no-cache">

    <title><%= [@title, app_name].compact.join(" - ") %></title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': 'reload'%>
    <%= yield :styles %>

    <%#= favicon_link_tag %>
    <%# favicon_link_tag "apple-touch-icon.png", :rel => "apple-touch-icon" %>

    <%= render 'layouts/external_js_libs' %>
    <%= yield :external_js_libs %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': 'reload' %>

    <%= yield :javascript %>
    <%= yield :head %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
  </head>
  <body class='<%= @body_class %>' data-js-libs='bootstrap fitie metis forms sidenav prism clipboard bs-switch <%= yield :js_libs %>'>

    <%= yield %>

  </body>
<% end %>

app/views/layouts/_dashboard_top_nav.html.erb
<nav class="navbar navbar-expand-lg my-0 justify-content-end inspectable">
  <!-- component-title: Top Nav Bar -->
  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item d-none d-lg-block">
        <a href="javascript:" class="SideNavToggle nav-link">
          <%= theme_icon_tag "menu" %>
        </a>
      </li>
<!--      <li class="nav-item">-->
<!--      </li>-->
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#">Disabled</a>-->
<!--      </li>-->
    </ul>
    <%= yield :navbar %>
    <ul class="nav navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link" id="dropdownSearchButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= theme_icon_tag "search" %>
        </a>
        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownSearchButton">
          <li>
            <form class="form-inline" role="search">
              <input type="text" class="form-control no-border no-border-radius" id="searchbox" placeholder="Not yet working">
            </form>
          </li>
        </ul>
      </li>
      <li class="nav-item">
        <%= link_to user_settings_path(current_user) do %>
          <a  data-toggle="modal" href="#settings-modal">
            <i class="fa fa-cog fa-2x settings"></i>
          </a>'
        <% end %>
      </li>
      <%= render partial: 'settings/edit' %>
<!--      <li class="nav-item dropdown">-->
<!--        <a class="nav-link" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
          <%#= theme_icon_tag "settings" %>
<!--          <span class="caret caret-light"></span>-->
<!--        </a>-->
<!--        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">-->
<!--          <li>-->
<!--            <a class="dropdown-item" href="#">Site management</a>-->
<!--          </li>-->
<!--          <li>-->
<!--            <a class="dropdown-item" href="#">User management</a>-->
<!--          </li>-->
<!--          <li>-->
<!--            <a class="dropdown-item" href="#">Settings</a>-->
<!--          </li>-->
<!--        </ul>-->
<!--      </li>-->
      <li class="nav-item dropdown notifications">
        <a class="nav-link with-count" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= theme_icon_tag "bell" %>
          <span class="badge badge-sm">2</span>
          <span class="d-none d-xs-block">Notifications</span>
        </a>
        <!-- dropdown -->
        <ul class="dropdown-menu  dropdown-menu-right">
          <li class="dropdown-item">
            <div class="card">
              <div class="card-header text-center text-primary">
                  <strong>You have
                    <span>0</span>
                    notifications</strong>
              </div>
              <div class="list-group">
                <% if current_user %>

                <a href="#" class="list-group-item">
                  <div class="media">
                    <%= random_avatar 32, "d-flex mr-3 rounded-circle" %>
                    <div class="media-body">
<!--                      <p><%#= current_user&.full_name if _user_signed_in?%> registered..</p>-->
                      <small class="text-muted d-block"><%= current_user.created_at %></small>
                    </div>
                  </div>
                </a>
                <a href="" class="media list-group-item">
                  <span class="media-body">
                    <div>
                      <p>You've reached your space quota!</p>
                      <div class="progress progress-sm m0">
                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
                          <span class="sr-only">100% Complete</span>
                        </div>
                      </div>
                    </div>
                    <small class="text-muted">12 hours ago</small>
                  </span>
                </a>
                  <% end %>
              </div>
              <div class="card-footer">
                <a href="#" class="pull-right">
                  <%= theme_icon_tag "settings" %>
                </a>
                <a href="#">View all Notifications</a>
              </div>
            </div>
          </li>
        </ul>
        <!-- / dropdown -->
      </li>
      <li class="nav-item dropdown user-nav">
        <a class="nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if user_signed_in? %>
            <%= image_tag(current_user.avatar, height:'64', width:'64', class: "avatar rounded-circle")%>
            <% else %>
            <%= random_avatar 64,  class: "avatar rounded-circle"%>
            <% end %>

          <span class="caret caret-light"></span>
        </a>
        <ul class="dropdown-menu dropdown-menu-right" role="menu">
          <li class="dropdown-item text-center">
            <div class="card">
              <div class="card-body">
                <span class="avatar img-rounded"><%= user_signed_in? ? image_tag(current_user.avatar) : random_avatar(120) %></span>
                <p class="m0 p0 d-block">
                  <%= user_signed_in? ? current_user.name : 'Fill' %>
                </p>
                <p class="small m0 p0">Premium Account</p>
              </div>
              <div class="card-footer d-flex justify-content-between">
                <div>
                  <a href="003_app_pages@fa-laptop%2F006_user_profile" class="btn ">
                    Edit Profile
                  </a>
                </div>
                <div>
                  <% if user_signed_in? %>
                    <%= link_to 'Logout', signout_path, class: 'btn' %>
                  <% else %>
                    <%= link_to 'Login', signin_path, class: 'btn' %>
                  <% end %>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

<script type="text/javascript" charset="utf-8">
$(function(){
  $('.settings').hover( function(){
    $(this).toggleClass('fa-spin')
  })
})
</script>

app/views/layouts/_flashes.html.erb
<% if alert %>
  <div class="alert alert-error">
    <a class="close" data-dismiss="alert">&times;</a>
    <%= fa_icon_tag "remove" %> <%= alert %>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-warning">
    <a class="close" data-dismiss="alert">&times;</a>
    <%= fa_icon_tag "info-sign" %> <%= notice %>
  </div>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_side_menu.html.erb
<nav class="nav-side-menu   navbar-expand-lg" >
  <%= render partial: 'layouts/side_menu_header' %>

  <div id="menu-content" class="navbar-collapse collapse">
    <div class="nav-side-container">
      <ul class="navbar-nav flex-column">
        <%= render partial: 'layouts/side_menu_main_content' %>
        <% if user_signed_in? %>

          <span id="external-ip" title="External IP" data-toggle="tooltip"><%= external_ip %></span>

          <li class="nav-item">
            <%= link_to profile_user_path(current_user.id), class: 'nav-link' do %>
              <%= fa_icon_tag('user', class: 'red') %>
              <span>Profile</span>
            <% end %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#" aria-expanded="false">
              <%#= theme_icon_tag "layout-menu-v" %>
              <i class="fa fa-server"></i>
              <span>Addresses</span>
              <span class="fa arrow"></span>
            </a>
            <ul class="nav-item nav-second-level collapse" aria-expanded="false">
              <li class="nav-item">
                <%= link_to 'Add Address', new_interface_path, class: 'nav-link' %>
              </li>
              <li class="nav-item hide">
                <%= link_to dashboard_user_path(current_user.id), class: 'nav-link' do %>
                  <%= fa_icon_tag('dashboard') %>
                  <span>Dashboard</span>
                <% end %>
              </li>
            </ul>
        <% end %>
        <li class="nav-item hide">
          <a class="nav-link" href="#" aria-expanded="false">
            <%= theme_icon_tag "layout-menu-v" %>
            <span>Multi-Level Menu</span>
            <span class="fa arrow"></span>
          </a>
          <ul class="nav-item nav-second-level collapse" aria-expanded="false">
            <li class="nav-item">
              <a href="#" class="nav-link">Second Level Item</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link">Second Level Item</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link" aria-expanded="false">
                <span>Third Level</span>
                <span class="fa arrow"></span>
              </a>
              <ul class="nav-item nav-third-level collapse">
                <li class="nav-item">
                  <a href="#" class="nav-link">Third Level Item</a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link">Third Level Item</a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link">Third Level Item</a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link" aria-expanded="false">
                    <span>Fourth Level</span>
                    <span class="fa arrow"></span>
                  </a>
                  <ul class="nav-item nav-fourth-level collapse" aria-expanded="false">
                    <li class="nav-item">
                      <a href="#" class="nav-link">Fourth Level Item</a>
                    </li>
                    <li class="nav-item">
                      <a href="#" class="nav-link">Fourth Level Item</a>
                    </li>
                    <li class="nav-item">
                      <a href="#" class="nav-link">Fourth Level Item</a>
                    </li>
                    <li class="nav-item">
                      <a href="#" class="active">Fourth Level Item</a>
                    </li>
                  </ul>
                </li>
              </ul>
              <!-- /.nav-third-level -->
            </li>
          </ul>
          <!-- /.nav-second-level -->
        </li>
        </ul>
    </div>
  </div>
</nav>
<style>
  #external-ip {
    text-align: center;
    padding: 2px;
    border-radius: 2px;
    background-color: #2E354F;
    color: #959FBD;
    display: inline;
    width: 50%;
    margin: 0 auto 2em auto;
    right: 15px;
    position:relative;
  }
</style>

app/views/layouts/_side_menu_header.html.erb
<div class="navbar-header d-none d-lg-block">
  <div class="profile">
    <%#= random_avatar 60, "rounded-circle profile-image" %>
    <%#= image_tag '/assets/ipwtf-logo.png', style: 'max-width: 85%; margin: auto;' %>
    <%= image_tag 'https://idkips.s3.us-east-2.amazonaws.com/ipwtf-logo.png', style: 'max-width: 85%; margin: auto;' %>
<!--    <div class="profile-body">-->
<!--      <h6><%#= current_user.full_name if user_signed_in? %></h6>-->
<!--      <div class="user-links">-->
<!--        <a class="btn btn-link" href="#" data-placement="bottom" data-toggle="tooltip" data-original-title="Profile">-->
          <%#= theme_icon_tag "user" %>
<!--        </a>-->
<!--        <a class="btn btn-link" href="mailto:bshyman@gmail.com'" data-placement="bottom" data-toggle="tooltip" data-original-title="Messages Eventually, Email me for now">-->
          <%#= theme_icon_tag "email" %>
<!--        </a>-->
<!--        <a class="btn btn-link" href="#" data-placement="bottom" data-toggle="tooltip" data-original-title="Settings">-->
          <%#= theme_icon_tag "settings" %>
<!--        </a>-->
<!--        <a class="btn btn-link" href="#" data-placement="bottom" data-toggle="tooltip" data-original-title="Logout">-->
          <%#= theme_icon_tag "power-off" %>
<!--        </a>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#menu-content" aria-controls="menu-content" aria-expanded="false" aria-label="Toggle navigation">

    <span class="navbar-toggler-icon"></span>
  </button>
</div>

app/views/layouts/application.html.erb
  <%= render :layout => "layouts/base" do %>
    <%= render "layouts/flashes" %>
    <%= yield %>
  <% end %>

app/views/layouts/devise.html.erb
<%= render :layout => "layouts/base" do %>
  <%= yield %>
<% end %>

app/views/layouts/email.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title><%= @title || message.subject %></title>
    <style type="text/css">

      /* Take care of image borders and formatting */
      img     { max-width:600px !important; outline:none; text-decoration:none; -ms-interpolation-mode: bicubic; }
      a img   { border:none; }

      /* Fix Apple contact links and hide the preheader */
      .applefix a           {color:#888888; text-decoration: none;}
      span[class="preheader"] { display:none; }

      tbody,
      tr,
      td {
        display: block;
        width: 100%;
      }

      /* Responsive Styles */
      @media only screen and (max-width:600px) {
        img                             { width:100% !important; height:auto !important; }
        img[class="columnImage"]        { height:auto !important; max-width:480px !important; width:100% !important; }
        table[id="emailContainer"]      { width:100% !important; }
        table[class="columnContainer"]  { width:100% !important; }
        table[class="mobileButton"]     { width:60% !important; }
        td[class="columnSingle"]        { display:block !important; width:100% !important; }
      }

    </style>
  </head>

  <body bgcolor="#efefef" style="background-color:#efefef; -webkit-text-size-adjust: none;">

    <span class="preheader" style="display:none; color:#efefef;"><%= @title || message.subject %></span>

    <table align="center" border="0" cellpadding="0" cellspacing="0" width="600" id="emailContainer" style="display:block; max-width:600px; background-color:#efefef;">
      <tr>
        <td align="center" valign="top">
          <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:600px;">
            <tr>
              <td>
                <%= render partial: 'emails/email_header', locals: { title: message.subject } %>
              </td>
            </tr>
            <%= yield %>
            <tr>
              <td>
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:600px;">
                  <tr>
                    <td align="center" valign="top">
                      <%= render partial: 'emails/email_footer' %>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>

  </body>
</html>

app/views/layouts/landing.html.erb
<%= render layout: "layouts/base" do %>
  <%= yield %>
<% end %>

app/views/layouts/scaffold.html.erb
<%= render "layouts/app_nav" do %>
  <div class="page-header  d-flex align-items-center mb-3">
    <div class='container'>
      <div class="row align-items-center">
        <div class="col-12 col-md-6">
          <h2 class='m-0 tracking-tighter'><%= @title %></h2>
          <%= yield :description %>
        </div>
        <div class="col-12 col-md-6">
          <%= yield :actions %>
        </div>
      </div>
    </div>
  </div><!-- /.page-header -->

  <div class='container'>
    <div class='row'>
      <div class="col-12">
        <%= render "layouts/flashes" %>
      </div>
    </div>
  </div>

  <%= yield %>
<% end %>

app/views/layouts/sidenav.html.erb
<%= render layout: "layouts/base" do %>
  <%= render partial: "layouts/side_menu" %>

  <div class="main-content">
    <%= render partial: 'layouts/dashboard_top_nav' %>

    <% if content_for?(:description) || content_for(:actions) %>
      <div class="scaffold page-header d-flex align-items-center mb-3">
        <div class='container'>
          <div class="row align-items-center">
            <div class="col-12 col-md-6">
              <% if content_for?(:description) %>
                <h2 class='m-0 tracking-tighter'><%= @title %></h2>
                <%= yield :description %>
              <% end %>
            </div>
            <div class="col-12 col-md-6">
              <% if content_for?(:actions) %>
                <%= yield :actions %>
              <% end %>
            </div>
          </div>
        </div>
      </div><!-- /.page-header -->
    <% end %>

    <div class="container pt-4">
      <%= render "layouts/flashes" %>
      <%= yield %>
    </div>

  </div>
<% end %>